obstacle_range: 2.5
raytrace_range: 3.5

footprint: [[0.31, 0.30], [-0.31, 0.30], [-0.31, -0.30], [0.31, -0.30]]

inflation_radius: 0.2
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: lidar, data_type: LaserScan, topic: lidar_topic, marking: true, clearing: true}